# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
"""
Django settings for my_campaign project.

Generated by 'django-admin startproject' using Django 1.8.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os
import ConfigParser

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONFIG_PATH = os.path.join(BASE_DIR, 'my_campaign/project-config.cfg')


# Config instance object
config = ConfigParser.RawConfigParser()

try:
    config.readfp(open(CONFIG_PATH))
except IOError, e:

    config.add_section("GENERAL")
    config.set("GENERAL", "secret_key", 'okq5rdq5wcoduw=3#bzq)&9e74(*cmlo@&+&1xfaw)bu3-v2(0')

    config.add_section("DATABASE")
    config.set("DATABASE", "engine", 'django.db.backends.sqlite3')
    config.set("DATABASE", "name", os.path.join(BASE_DIR, 'db.sqlite3'))
    config.set("DATABASE", "user", "")
    config.set("DATABASE", "password", "")
    config.set("DATABASE", "host", "")
    config.set("DATABASE", "port", "")

    config.add_section("LOCALE")
    config.set("LOCALE", "code", 'pt-br')
    config.set("LOCALE", "timezone", 'America/Bahia')
    config.set("LOCALE", "i18n", 'true')
    config.set("LOCALE", "l10n", 'true')
    config.set("LOCALE", "tz", 'true')


    with open(CONFIG_PATH, 'wb') as configfile:
        config.write(configfile)
        configfile.close()

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config.get("GENERAL", "secret_key")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'experience'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'my_campaign.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_campaign.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config.get("DATABASE", "engine"),
        'NAME': config.get("DATABASE", "name"),
    }
}


if config.get("DATABASE", "user"):
    DATABASES['default']['USER'] = config.get("DATABASE", "user")

if config.get("DATABASE", "password"):
    DATABASES['default']['PASSWORD'] = config.get("DATABASE", "password")

if config.get("DATABASE", "host"):
    DATABASES['default']['HOST'] = config.get("DATABASE", "host")

if config.get("DATABASE", "port"):
    DATABASES['default']['PORT'] = config.get("DATABASE", "port")



# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = config.get("LOCALE", "code")
TIME_ZONE = config.get("LOCALE", "timezone")
USE_I18N = config.getboolean("LOCALE", "i18n")
USE_L10N = config.getboolean("LOCALE", "l10n")
USE_TZ = config.getboolean("LOCALE", "tz")


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

LOGIN_URL = '/login'
